export const myProjects = [
  {
    id: 1,
    title: "React Project",
    p: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat laboriosam cupiditate possimus veniam modi",
    category: ["react", "tailwind"],
    imgPath: "../../public/imegs/1.jpg",
    link: "#",
    gitHub: "#",
  },
  {
    id: 2,
    title: "css Project",
    p: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat laboriosam cupiditate possimus veniam modi",
    category: "css",
    imgPath: "../../public/imegs/2.jpg",
    link: "#",
    gitHub: "#",
  },
  {
    id: 3,
    title: "javascript Project",
    p: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat laboriosam cupiditate possimus veniam modi",
    category: "javascript",
    imgPath: "../../public/imegs/3.jpg",
    link: "#",
    gitHub: "#",
  },
  {
    id: 4,
    title: "Bootstrbe Project",
    p: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat laboriosam cupiditate possimus veniam modi",
    category: "tailwind",
    imgPath: "../../public/imegs/4.jpg",
    link: "#",
    gitHub: "#",
  },
  {
    id: 5,
    title: "tailwind Project",
    p: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat laboriosam cupiditate possimus veniam modi",
    category: "tailwind",
    imgPath: "../../public/imegs/5.jpg",
    link: "#",
    gitHub: "#",
  },
  {
    id: 6,
    title: "css Project",
    p: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat laboriosam cupiditate possimus veniam modi",
    category: "css",
    imgPath: "../../public/imegs/6.jpg",
    link: "#",
    gitHub: "#",
  },
  {
    id: 7,
    title: "React Project",
    p: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat laboriosam cupiditate possimus veniam modi",
    category: "react",
    imgPath: "../../public/imegs/7.jpg",
    link: "#",
    gitHub: "#",
  },
  {
    id: 8,
    title: "React Project",
    p: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat laboriosam cupiditate possimus veniam modi",
    category: "react",
    imgPath: "../../public/imegs/8.jpg",
    link: "#",
    gitHub: "#",
  },
  {
    id: 9,
    title: "React Project",
    p: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat laboriosam cupiditate possimus veniam modi",
    category: "react",
    imgPath: "../../public/imegs/9.jpg",
    link: "#",
    gitHub: "#",
  },
];
